## PA- 7.1

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors, KNeighborsClassifier
from sklearn.datasets import load_digits, load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, Normalizer
from sklearn.linear_model import LogisticRegression, SGDRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, f1_score, classification_report, mean_squared_error, r2_score

In [ ]:
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

In [ ]:
count_vec = CountVectorizer()
X_c = count_vec.fit_transform(text_data)

In [ ]:
X_c.shape

(9, 99)

In [ ]:
print(X_c)

  (0, 51)	1
  (0, 43)	1
  (0, 53)	1
  (0, 55)	1
  (0, 2)	1
  (0, 94)	1
  (0, 98)	1
  (0, 26)	1
  (0, 57)	1
  (0, 77)	1
  (0, 15)	1
  (1, 43)	1
  (1, 55)	1
  (1, 35)	1
  (1, 29)	1
  (1, 5)	1
  (1, 71)	1
  (1, 25)	1
  (1, 86)	2
  (1, 84)	1
  (1, 56)	1
  (1, 18)	1
  (1, 7)	2
  (1, 34)	1
  (1, 44)	1
  :	:
  (7, 64)	1
  (7, 69)	1
  (7, 82)	1
  (7, 65)	1
  (7, 0)	1
  (7, 38)	1
  (7, 63)	1
  (7, 91)	1
  (7, 3)	1
  (7, 6)	1
  (7, 14)	1
  (7, 96)	1
  (8, 77)	1
  (8, 5)	1
  (8, 86)	1
  (8, 7)	1
  (8, 80)	1
  (8, 28)	1
  (8, 13)	1
  (8, 24)	1
  (8, 49)	1
  (8, 93)	1
  (8, 30)	1
  (8, 37)	1
  (8, 95)	1


In [ ]:
count_vec.vocabulary_

{'metaverse': 51,
 'is': 43,
 'network': 53,
 'of': 55,
 '3d': 2,
 'virtual': 94,
 'worlds': 98,
 'focused': 26,
 'on': 57,
 'social': 77,
 'connection': 15,
 'in': 35,
 'futurism': 29,
 'and': 5,
 'science': 71,
 'fiction': 25,
 'the': 86,
 'term': 84,
 'often': 56,
 'described': 18,
 'as': 7,
 'hypothetical': 34,
 'iteration': 44,
 'internet': 41,
 'single': 75,
 'universal': 88,
 'world': 97,
 'that': 85,
 'facilitated': 23,
 'by': 12,
 'use': 90,
 'augmented': 8,
 'reality': 68,
 'headsets': 33,
 'has': 31,
 'its': 46,
 'origins': 58,
 '1992': 1,
 'novel': 54,
 'snow': 76,
 'crash': 17,
 'portmanteau': 62,
 'meta': 50,
 'universe': 89,
 'various': 92,
 'metaverses': 52,
 'have': 32,
 'been': 9,
 'developed': 19,
 'for': 27,
 'popular': 61,
 'such': 81,
 'platforms': 60,
 'like': 48,
 'second': 72,
 'life': 47,
 'some': 78,
 'iterations': 45,
 'involve': 42,
 'integration': 39,
 'between': 10,
 'physical': 59,
 'spaces': 79,
 'economies': 21,
 'including': 36,
 'significant': 74,
 '

In [ ]:
cvec2=CountVectorizer(min_df=2)
X_c2 = cvec2.fit_transform(text_data)

In [ ]:
X_c2.shape

(9, 20)

In [ ]:
Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]

In [ ]:
cvec3=CountVectorizer(max_features=10)
X_c3=cvec3.fit_transform(Docs)

In [ ]:
print(X_c3.toarray())

[[0 0 1 1 0 1 0 1 0 1]
 [0 2 0 1 0 0 1 1 0 1]
 [1 0 0 1 1 0 0 1 1 1]]


In [ ]:
X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]])
p= np.asarray([[0,0,0]])
k=1
neigh = NearestNeighbors(n_neighbors=k)
neigh.fit(X)
print(neigh.kneighbors(p))

(array([[101.74969287]]), array([[2]]))


In [ ]:
X,y = load_digits(return_X_y=True)

In [ ]:
X.shape

(1797, 64)

In [ ]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.unique(y, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180]))

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2, random_state=10)
ssc=StandardScaler()
softmax_reg=LogisticRegression(multi_class='multinomial', solver='sag')
pipepa = Pipeline(steps=[("ssc",ssc),("smr", softmax_reg)])
pipepa.fit(X_train,y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Pipeline(steps=[('ssc', StandardScaler()),
                ('smr',
                 LogisticRegression(multi_class='multinomial', solver='sag'))])

In [ ]:
y_pred = pipepa.predict(X_train)
accuracy_score(y_train ,y_pred)

0.9951287404314544

In [ ]:
y_pred_test = pipepa.predict(X_test)
accuracy_score(y_test, y_pred_test)

0.9694444444444444

In [ ]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.91      0.94        34
           2       0.89      1.00      0.94        34
           3       1.00      0.95      0.97        40
           4       1.00      0.94      0.97        34
           5       0.94      1.00      0.97        32
           6       1.00      0.97      0.99        37
           7       1.00      1.00      1.00        40
           8       0.89      0.97      0.93        33
           9       1.00      0.95      0.97        39

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



## GA-7 Part-A

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/data/data_for_large_scale.csv')

In [ ]:
data

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0         -1.580     1.0500     1.0600     -0.440    0.45100    -0.0348   
1         -0.832    -0.8660    -1.3400      0.138    1.18000     0.7330   
2         -0.237     2.0900    -3.9300      0.296    0.35200    -0.5010   
3         -1.170    -1.1300    -1.0900      1.120    0.31200     0.1830   
4          0.260    -0.0273     0.9250     -1.150   -1.39000     0.0251   
...          ...        ...        ...        ...        ...        ...   
89995     -0.268    -0.3200    -0.0146     -0.251    1.76000     0.8590   
89996     -0.774     0.4960     1.9400      0.673    0.29500    -0.0137   
89997      0.509    -0.3220     0.6810     -0.276   -0.00553    -1.1000   
89998      0.360     1.2500     0.6510     -0.871    0.37900     0.7690   
89999     -0.860    -0.6010     0.7390      0.190   -0.33100    -1.2700   

       Feature-7  Feature-8  Feature-9  Feature-10  Target  
0          0.643     0.2650      0.268     -0.8510   84.70  
1         -1.410     0.1350     -0.088     -1.5500 -211.00  
2          0.961    -0.0287      1.820      0.9380  -96.90  
3          0.448    -0.8190     -1.010     -1.0800 -152.00  
4          0.627     0.0950     -0.280     -0.8480  -57.70  
...          ...        ...        ...         ...     ...  
89995     -1.090    -1.3800      1.760     -1.0900   -4.15  
89996     -0.966    -0.6270     -0.113      0.0767   63.50  
89997      0.453     0.7270     -1.940     -2.0100  -80.20  
89998      1.330    -0.3670     -1.280     -1.1000  158.00  
89999     -2.610    -0.4830     -1.380      1.1100 -369.00  

[90000 rows x 11 columns]

In [ ]:
X,y = data.iloc[:,0:10],data.iloc[:,10]

In [ ]:
np.unique(X.iloc[:,0])

array([-4.28, -4.03, -4.01, ...,  4.01,  4.08,  4.1 ])

In [ ]:
X_array,y_array = X.to_numpy(), y.to_numpy()
X_train,X_test,y_train,y_test = train_test_split(X_array,y_array, test_size=0.3, random_state=10)

In [ ]:
X_test.shape

(27000, 10)

In [ ]:
X_train=X_train.reshape(700, 90, 10)
X_test=X_test.reshape(300, 90, 10)
y_train=y_train.reshape(700, 90, 1)
y_test=y_test.reshape(300, 90, 1)

In [ ]:
sgd_reg = SGDRegressor()
np.unique(y_train)

array([-790., -776., -746., ...,  734.,  741.,  810.])

In [ ]:
y_train.shape

(700, 90, 1)

In [ ]:
iter=1
for iter in range(700):
  if iter==1:
    sgd_reg.partial_fit(X_train[iter,:,:],y_train[iter,:,:])
    #np.unique(y_train) not used in partial fit, why?
  else:
    sgd_reg.partial_fit(X_train[iter,:,:],y_train[iter,:,])

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example 

In [ ]:
y_pred=sgd_reg.predict(X_test.reshape(27000,10))
ytest=y_test.reshape(27000, 1)
y_pred.shape

(27000,)

In [ ]:
print(r2_score(ytest,y_pred))
print(mean_squared_error(ytest,y_pred))

0.9999919793815162
0.30583346229736147


In [ ]:
sgd_reg.intercept_

array([-0.00482031])

In [ ]:
sgd_reg.coef_

array([51.32111517, 22.26559559, 81.23787974, 53.19653085, 76.46597305,
       71.47208659, 93.45081668, 51.92203337, 30.03922091, 40.95637341])

Q6-8

In [ ]:
ss=StandardScaler()
sr=SGDRegressor(random_state=10)
epoch=1
chunksize=20000
for iter in pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt", header=None, names=['OSM_ID', 'LONGITUDE', 'LATITUDE', 'ALTITUDE'], chunksize=chunksize, iterator=True):
  ss.partial_fit(iter)
  iter = ss.transform(iter)
  X_train_p=iter[:,0:3]
  y_train_p=iter[:,3]
  sr.partial_fit(X_train_p, y_train_p)
  print("iteration: ", epoch, "intercept: ", sr.intercept_, "coeff: ", sr.coef_)
  epoch+=1

iteration:  1 intercept:  [-0.02690111] coeff:  [ 0.10026097  0.27495964 -0.19300723]
iteration:  2 intercept:  [-0.09373523] coeff:  [ 0.19833572  0.00895477 -0.06097604]
iteration:  3 intercept:  [0.00079471] coeff:  [ 0.31227267  0.11015889 -0.0243527 ]
iteration:  4 intercept:  [-0.03782414] coeff:  [ 0.17077248  0.21145702 -0.21144595]
iteration:  5 intercept:  [-0.04332028] coeff:  [ 0.07764607  0.05642888 -0.03577181]
iteration:  6 intercept:  [-0.09399112] coeff:  [ 0.0500058   0.21943601 -0.29708919]
iteration:  7 intercept:  [-0.04770028] coeff:  [-0.00974607  0.25435704 -0.28071577]
iteration:  8 intercept:  [0.1039192] coeff:  [ 0.17372434  0.2412959  -0.2457776 ]
iteration:  9 intercept:  [0.1127235] coeff:  [ 0.17036364  0.28058496 -0.2862584 ]
iteration:  10 intercept:  [-0.02641055] coeff:  [ 0.22760954  0.18667585 -0.21964396]
iteration:  11 intercept:  [-0.05764344] coeff:  [ 0.13506302 -0.04538301  0.03519571]
iteration:  12 intercept:  [-0.04051696] coeff:  [ 0.0332

In [ ]:
iris = load_iris()
X3,y3=iris.data,iris.target

In [ ]:
X_train3,X_test3,y_train3,y_test3 = train_test_split(X3,y3, test_size=0.2, random_state=10)
norm = Normalizer()
knc = KNeighborsClassifier(n_neighbors=1)
pipe = Pipeline([('scaler', Normalizer()),('knc', KNeighborsClassifier(n_neighbors=1))])
param_grid = {'knc__n_neighbors':[2,3,4]}
gscv = GridSearchCV(pipe, param_grid=param_grid, scoring='accuracy')
gscv.fit(X_train3, y_train3)

GridSearchCV(estimator=Pipeline(steps=[('scaler', Normalizer()),
                                       ('knc',
                                        KNeighborsClassifier(n_neighbors=1))]),
             param_grid={'knc__n_neighbors': [2, 3, 4]}, scoring='accuracy')

In [ ]:
print(gscv.best_estimator_)

Pipeline(steps=[('scaler', Normalizer()),
                ('knc', KNeighborsClassifier(n_neighbors=3))])


In [ ]:
y_pred = gscv.best_estimator_.predict(X_test3)
print(classification_report(y_test3, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.92      0.96        13
           2       0.88      1.00      0.93         7

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

